#!/bin/bash

################################################################################
# apt-mirror
################################################################################
# launches apt-mirror, then does some housekeeping 
################################################################################

if [ $# -ne 0 ]
then
  printf "\n\nUsage:\n\t$0\n\n"
  exit 1
fi

trap "do_stop" 9 15

do_stop()
{
  echo "Stopped"
  exit 1
}

LCK=/var/spool/apt-mirror/var/apt-mirror.lock

if [ -r "$LCK" ]
then
  #look for stale locks
  echo "stale lock detected in $LCK..."
  DES=`ps ax | grep wget | grep apt-mirror`
  NUM=`ps ax | grep wget | grep apt-mirror | wc -l`
  if [ "$NUM" -eq 0 ]
  then
    echo "No actual downloads taking place right now, deleting stale lock at $LCK..."
    rm -f "$LCK"
  else
    echo "A lock is active ($LCK) and $NUM downloads taking place right now:"
    printf "$DES"
    printf "\n\nexiting...\n"
    exit 1
  fi
fi

touch "$LCK"

export WGETRC=/root/.wgetrc

echo "executing apt-mirror..."
/usr/bin/apt-mirror

echo "executing clean.sh..."
/var/spool/apt-mirror/var/clean.sh

echo "fixing archive.canonical.com..."
/util/apt-mirror.fix.archive.canonical.com

echo "Deleting $LCK..."
rm -f "$LCK"

date

echo "done!"
