#!/bin/bash

alarma()
{
  cnt=1;
  while [ $cnt -le $1 ]
  do
    printf "\a"
    sleep 1
    cnt=`expr $cnt + 1`
  done
}

while true
do
if [ `who | cut -f1 -d' ' | sort |uniq | wc -l` -gt 1 ]
then
  echo No Estas Solo...
  alarma 3
  exit 1
fi
sleep 1
done
