#rm -rf /usr/dict
#rm -rf /usr/local/crack

CRACK_DIR=/usr/local/crack
CRACK_SRC=/zip/crack

mkdir /usr/dict >/dev/null 2>&1

cp $CRACK_SRC/words* /usr/dict
cd /usr/dict
gunzip *.gz

mkdir $CRACK_DIR
cd $CRACK_DIR

#Descomprime programa y parche MA
tar zxvf $CRACK_SRC/crack*.tar.gz
tar zxvf $CRACK_SRC/patch*.tar.gz

chown -R root.root $CRACK_DIR

cd c*

chmod u+x Crack

#Necesario para RH y otros sistemas que usan MD5 en crypt
mv src/libdes src/libdes,orig
cd src/util
cp elcid.c,bsd elcid.c

cd ../..

Crack -makeonly
Crack -makedict
