#!/bin/bash

if [ $# -eq 0 ]
then
  printf "\nUso:\n\t$0 carpeta ...\n\n"
  exit 1
fi


echo "# toxine playlist" 

for CARPETA in $* 
do
    ( ls -1 $CARPETA *.avi *.mpg *.mpeg *.divx *.asf *.wmv 2>/dev/null ) |  xargs -I '{}' printf "entry {\n\tidentifier = %s;\n\tmrl = %s;\n};\n\n" '{}' '{}' 
	
done

echo "# END" 
