#!/bin/bash

################################################################################
# delay
################################################################################
# copy from stdin to stdout sleeping between lines
# example: ls -l | delay 0.75
################################################################################

if [ $# -ne 1 ]
then
  printf "\n\nUsage:\n\t$0 delay-in-seconds\n\n\n"
  exit 1
fi

T=$1

while true 
do
  read A
  sleep $T
  echo $A
done
