#!/bin/sh

export PATH=/etc/rc.d/init.d:/bin:/sbin:/usr/bin:/usr/sbin:/util

if [ $# -ne 0 ]
then
  printf "Uso:\n\t$0\n\n"
  exit 1
fi

A="192.168.4.0/24"
disable-ip $A
echo "Dirección $A desactivada"
