#!/bin/sh

export PATH=/etc/rc.d/init.d:/bin:/sbin:/usr/bin:/usr/sbin:/util

if [ $# -ne 0 ]
then
  printf "Uso:\n\t$0\n\n"
  exit 1
fi

for A in `serie 1 15 1 192.168.1.`
do  
  disable-ip $A
  echo "Dirección $A desactivada"
done
