#!/bin/sh

export PATH=/etc/rc.d/init.d:/bin:/sbin:/usr/bin:/usr/sbin:/util

if [ $# -eq 0 ]
then
  printf "Uso:\n\t$0 dirección-ip[/mascara] ...\n\n"
  exit 1
fi

for A in $*
do
#logger user.info "Activando $A en el cortafuegos"
   
  #Borra reglas 
  ipchains -D input -i eth0 -s $A -p tcp -d 0.0.0.0/0 www -j REJECT
  ipchains -D input -i eth0 -s $A -p tcp -d 0.0.0.0/0 81 -j REJECT
  ipchains -D input -i eth0 -s $A -p tcp -d 0.0.0.0/0 3128 -j REJECT
  ipchains -D input -i eth0 -s $A -p tcp -d 0.0.0.0/0 ftp -j REJECT
done
