#!/bin/bash

################################################################################
# factorial
################################################################################
# computes n!  (n>=0, integer)
# for n<0 and n not integer you will need the gamma function
################################################################################

if [ $# -ne 1 ]
then
  printf "\n\nUsage:\n\t$0 n\n\n"
  exit 1
fi

#discard fractional part
N=${1%.*}

if [ $N -lt 0 ]
then
  printf "\n\nError, n>=0\n\n"
  exit 1
fi

if [ $N -eq 0 ]
then
	echo 1
else
	Z=$(/util/factorial $(BC_LINE_LENGTH=0 bc <<< "$N - 1" ))
	echo $(BC_LINE_LENGTH=0 bc <<< "$N * $Z")
fi
