#!/bin/bash

################################################################################
# fibonacci
################################################################################
# computes fibonacci(n)  (n>=0, integer)
################################################################################

if [ $# -ne 1 ]
then
  printf "\n\nUsage:\n\t$0 n\n\n"
  exit 1
fi

if [ $1 -lt 0 ]
then
  printf "\n\nn>=0\n\n"
  exit 1
fi

if [ $1 -eq 0 -o $1 -eq 1 ]
then
	echo $1
else
	n0=0
	n1=1
	i=$1
	while [ $i -ge 2 ]
	do
	  let s=$n0+$n1
	  let n0=$n1
	  let n1=$s
	  let "i--"
	done
	echo $s
fi
