#!/bin/bash

################################################################################
# forward
################################################################################
# displays/modifies ip_forward
################################################################################

if [ $# -gt 1 ]
then
	printf "\n\nUsage:\n\t$0 [ on | off ]\n\n" 
	exit 1
fi


if [ -z "$1" ]
then
	printf "\n\n/proc/sys/net/ipv4/ip_forward is $(cat /proc/sys/net/ipv4/ip_forward)\n\n"
elif [ "$1" == "on" ]
then
	echo 1 > /proc/sys/net/ipv4/ip_forward
elif [ "$1" == "off" ]
then
	echo 0 > /proc/sys/net/ipv4/ip_forward
else
	echo "Error"
	exit 1
fi
