#!/bin/sh
# description: Frox - FTP Proxy that supports transparent proxying
# chkconfig: 2345 99 00

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
progname="Frox"
configfile="/etc/frox.conf"
options="-f $configfile"
frox=/usr/local/sbin/frox
pidfile=`grep "^PidFile" $configfile | awk '{ print $2 }'`

if [ "$pidfile" = "" ]; then
    pidfile="/var/run/frox.pid"
fi

stop() {
    echo -n $"Stopping $progname: "
    killproc $frox
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/frox
}

start() {
    echo -n $"Starting $progname: "
    $frox $options
    echo "===>$frox $options"
    action "" /sbin/pidof $frox
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/frox
}

status() {
    if [ -f $pidfile ]; then
        echo -n $"$progname (pid `cat $pidfile`) is running..."
        action "" /sbin/pidof $frox
        RETVAL=0
    else
        echo $"$progname is stopped..."
        RETVAL=1
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    condrestart)
        [ -f /var/lock/subsys/frox ] && restart || :
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|condrestart|status}"
        RETVAL=1
esac

exit $RETVAL
