#!/bin/sh
#prepara el puerto y usa el dialer indicado

DIALER=$1.dialer
PROVEEDOR=$2.proveedor
DNS=$2.dns
BLOQUEO=/var/lock/internet

if [ $# -ne 2 -o ! -f /etc/ppp/$DIALER -o ! -f /root/$PROVEEDOR -o ! -f /root/$DNS ]
then

if [ $# -ne 2 ]
then
printf "Número de parámetros incorrecto\n\n"
fi
if [ ! -f /etc/ppp/$DIALER ]
then
printf "No existe el .dialer especificado en /etc/ppp\n\n"
fi
if [ ! -f /root/$PROVEEDOR -o ! -f /root/$DNS ]
then
printf "No existe el .proveedor especificado en /home (o su .dns)\n\n"
fi 

printf "Uso: $0 <dialer> <proveedor>\n\n"
printf "Dialers disponibles en /etc/ppp:\n"
ls /etc/ppp/*.dialer | cut -f1 -d'.' | cut -f4 -d'/'
printf "\n"
printf "Proveedores disponibles en  /root:\n"
ls /root/*.proveedor | cut -f1 -d'.' | cut -f3 -d'/'
printf "\n"
exit 1
fi

echo Espere...
#Crear "cuenta" enlazado al proveedor apropiado. Contiene login y clave
ln -fs /root/$PROVEEDOR /root/cuenta

#Poner un bloqueo para evitar rellamada
if [ -f $BLOQUEO ]
then
echo "Bloqueo $BLOQUEO encontrado. Terminando."
exit 1
fi
touch $BLOQUEO

#Preparar el fichero de DNS
ln -fs /root/$DNS /var/named/resolv.conf

#Preparar el root.cache
ln -fs /var/named/root.cache.internet /var/named/root.cache

#relanzar servicio named
/etc/rc.d/init.d/named restart >/dev/null 2>&1 &

#Ejecutar ppp con el dialer adecuado
printf "pppd: conectando ($DIALER)...\n"
exec /usr/sbin/pppd connect /etc/ppp/$DIALER /dev/modem 115200
printf "pppd: ejecutado\n"
