#!/bin/bash

key()
{
  gpg --keyserver subkeys.pgp.net --recv $1
  gpg --export --armor $1 | sudo apt-key add -
}

KEYS="437D05B5 1135D466 DD4D5088 6A423791 12B83718 4B6E7209 80DF6D58 E8BDA4E3 52ABFCB1 E394D996 969F3F57 521A9C7C 887D9FD2 "
KEYS="${KEYS} 8ABD1965 2EE24E0B 81836EBF DD800CD9"

for K in $KEYS
do
  key $K
done

wget http://ubuntu.uni-klu.ac.at/uniklu-debuild.pub
sudo apt-key add uniklu-debuild.pub 
