#!/bin/sh

if [ $# -lt 3 -o $# -gt 4 ]
then
printf "Uso\n\t$0 inicio fin incremento [prefijo]\n\n"
exit 1
fi

if [ $3 -eq 0 ]
then
exit 1
fi

for i in $(seq $1 $3 $2)
do
  echo $4$i
done

exit 0

A=$1
while [ $A -le $2 -a $3 -gt 0 -o $A -ge $2 -a $3 -lt 0 ]
do
echo $4$A
A=`expr $A \+ $3`
done
