#!/bin/bash

###############################################################################
# temp_control
###############################################################################
# controls temp variables issues mail alerts in case the situation recommends it
# REQUIRED PACKAGES: lm-sensors mailutils
# Parameters:
#  tempVar: variable (from sensors) to be checked
#  tWarning: send warnings it temp equals or over tWarning
#  tHalt: hslt system if temp reached
#  tSleep:  pause (seconds) before system halt
#  email: receivers of alerts
###############################################################################

if [ $# -lt 5 ]
then
  printf "\n\nUsage:\n\t$0 tempVar tWarning tHalt tSleep email...\n\nYour sensors:\n"
  sensors
  printf "\n\n"
  exit 1
fi

tempVar=$1
tWarning=$2
tHalt=$3
tSleep=$4
shift
shift
shift
shift
to="$*"

temp=`sensors|grep "$tempVar" |cut -d "+" -f2 | cut -d "." -f1 | sed '2,$d'`
subject="Host: $HOSTNAME: temperature is too high (${temp} C)"

if [ $temp -ge ${tWarning} ]
then
  tmp=`tempfile`
  fecha=`date "+%Y%m%d_%H%M%S"`
 
  printf "*Date: ${fecha}*\n" > $tmp 
  printf "*Temperature: ${temp}*\n" >> $tmp
  printf "*Host: ${HOSTNAME}*\n" >> $tmp
  printf "\n\n" >> $tmp

  if [ ${temp} -ge ${tHalt} ]; then
         logger -s "CRITICAL ALERT: Temperature of host $HOSTNAME is $temp C!!! (extremely high)" 2>> $tmp
         logger -s "Shutting $HOSTNAME down in $tSleep seconds..." 2>> $tmp
         printf "\n\nTOP:\n" >> $tmp
         top -b -n 1 >> $tmp
         cat $tmp|mailx -s "*HALT* $subject" ${to}
	 cat $tmp
	 sleep  $tSleep
	 init 0
  elif [ ${temp} -gt ${tWarning} ]; then
         logger -s "WARNING: Temperature of host $HOSTNAME is $temp C!!!. Will shut down if temp goes beyond $tHalt C" 2>> ${tmp}
         printf "\n\nTOP:\n" >> $tmp
         top -b -n 1 >> $tmp
         cat $tmp|mailx -s "$subject" ${to}
	 cat $tmp
	 exit 0
  fi

else 
  logger -s "Host: $HOSTNAME, Temperature: ${temp} C" 
  exit 0
fi
