#!/bin/bash

PATH=/util/videotools:/util:$PATH
BUILDPATH=/usr/src

ejecutar()
{
  printf "Ejecutando: $1...\n\n"
  sh -c "$1"
}

LDCONF="/usr/local/lib"

echo Configurando repositorio medibuntu...
DIST=`lsb_release -cs`

echo Su distro es $DIST

echo "Configurando repositorios Medibuntu..."
sudo wget http://www.medibuntu.org/sources.list.d/${DIST}.list --output-document=/etc/apt/sources.list.d/medibuntu.list
sudo apt-get --yes update && sudo apt-get --yes --force-yes install medibuntu-keyring && sudo apt-get --yes update

echo "Instalando build-essential, git-core, ..."
ejecutar "sudo apt-get --yes install cvs build-essential git-core automake libtool libxcb-shm0-dev yasm checkinstall libtool autopoint"

echo "Eliminando paquetes innecesarios..."
ejecutar "sudo apt-get --yes autoremove"

echo "Configurando /etc/ld.so.conf..."
fgrep --line-regexp --quiet "$LDCONF" /etc/ld.so.conf
if [ $? -ne 0 ]
then
  sudo echo "$LDCONF" >> /etc/ld.so.conf
  ldconfig
fi
