#!/bin/bash

BUILDPATH=/usr/src
VERSION=0.1.2

ejecutar()
{
  printf "Ejecutando: $1...\n\n"
  sh -c "$1"
}


#BUILD
echo Construyendo libopencore-amr...
ejecutar "apt-get --yes remove libopencore-amrwb-dev libopencore-amrnb-dev libopencore-amrwb0 libopencore-amrnb0 libamrnb-dev libamrwb-dev"
cd $BUILDPATH
wget --continue http://transact.dl.sourceforge.net/project/opencore-amr/opencore-amr/$VERSION/opencore-amr-$VERSION.tar.gz && \
tar xvf opencore-amr-$VERSION.tar.gz && \
cd opencore-amr-$VERSION && \
./configure --prefix=/usr/local && \
make && \
checkinstall --fstrans=no --install=yes --pakdir "$HOME/Desktop" \
--maintainer "$USER" --pkgname="libopencore-amr" --pkgversion="$VERSION"  \
--backup=no --deldoc=yes --deldesc=yes --delspec=yes --gzman --default && \
make distclean
